[package]
name = "rust_htmx_tera_project"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tera = "1.14"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls"] }
